Updates tests

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -1,4 +1,4 @@
-name: Run Tests
+name: Analyze & Run Tests
 on:
   pull_request:
     branches: [master]
@@ -16,3 +16,21 @@ jobs:
           flutter-version: '1.12.13+hotfix.9'
       - run: flutter pub get
       - run: flutter test
+  analyzer:
+    name: Analyzer
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v1
+      - uses: axel-op/dart-package-analyzer@v2.0.0
+        with:
+          githubToken: ${{ secrets.GITHUB_TOKEN }}
+      - name: Analyzer Output
+        run: |
+          ERRORS=${{ steps.analysis.outputs.errors }}
+          WARNINGS=${{ steps.analysis.outputs.warnings }}
+          HINTS=${{ steps.analysis.outputs.hints }}
+          if (( $(echo "$ERRORS > 0" | bc) )) || (( $(echo "$WARNINGS > 0" | bc) )) || (( $(echo "$HINTS > 0" | bc) ))
+          then
+            echo "Found issues, please check Analysis file for more information"
+            exit 1
+          fi
